### ISSUE TITLE
Fehlermeldung beim Ausführen:

### ISSUE THREAD

**Issue by cannondale-f500** [ChaoticSomeone/ooen_mining#1]
Folgende Fehlermeldung wurde mit dem RaspberryPI ausgegeben:
python3 scraper.py
.    Traceback (most recent call last):
  File "/tmp/ooen_mining-main/scraper.py", line 91, in <module>
    prevData = json.load(f)
  File "/usr/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by ChaoticSomeone** [comment]
Liegt daran, dass die Datei data.json manuell erstellt wurde. Werd demnächst sicherstellen, dass das nicht mehr passieren kann :)
